---
- name: Add PPAs
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:keithw/mosh
    - ppa:klaus-vormweg/awesome
    - ppa:otto-kesselgulasch/gimp
    - ppa:videolan/stable-daily
    - ppa:lestcape/cinnamon

- name: Install graphical environments
  apt: name={{ item }} state=present
  with_items:
    - awesome
    - cinnamon
    - i3

- name: Install and update default packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - eclipse
    - emacs
    - firefox
    - gap
    - gimp
    - gimp-data
    - gimp-data-extras
    - gimp-plugin-registry
    - git
    - htop
    - inkscape
    - libreoffice
    - mlocate
    - mosh
    - mpv
    - openjdk-7-jdk
    - redshift
    - rxvt-unicode-256color
    - sl
    - spim
    - tcpdump
    - texlive
    - texmaker
    - texstudio
    - tmux
    - ubuntu-restricted-extras
    - vim-gtk
    - vlc
    - wine
    - zsh

- name: Make folders for dconf configuration
  file: path=/etc/dconf/db/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - profile
    - local.d

- name: Global dconf configuration
  copy: src=etc/dconf/{{ item }} dest=/etc/dconf/{{ item }} owner=root group=root mode=0644
  with_items:
    - db/profile/user
    - db/local.d/user-switching
