---
- include_vars: wps.yml

- name: Check for WPS Office
  stat: path=/opt/kingsoft/{{ wpsUrl | regex_replace('.*/', '') }}
  register: wps

- name: Download WPS Office
  get_url: url={{ wpsUrl }} dest=/opt/kingsoft/{{ wpsUrl | regex_replace('.*/', '') }}
  when: wps.stat.exists == False

- name: Install WPS Office
  apt: deb=/opt/kingsoft/{{ wpsUrl | regex_replace('.*/', '') }} state=present
  when: wps.stat.exists == False

- name: Install Microsoft Fonts
  apt: name=ttf-mscorefonts-installer state=present
  notify: fonts
